version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 192.168.50.1
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/New_York'
      PIHOLE_DNS_: '192.168.50.1'
      DNSSEC: 'true'
      TEMPERATUREUNIT: 'c'
      WEBTHEME: 'default-auto'
      WEBPASSWORD_FILE: '/run/secrets/pihole-webpassword'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)
    restart: unless-stopped
    secrets:
      - pihole-webpassword
secrets:
  pihole-webpassword:
    file: '../.secrets/pihole_webpassword.txt'
